SDK update, Selectors update
emastra/google-shopping-scraper-puppeteer pull request #15
Opened 2021-05-25 21:17 UTC by OlehVeselov92

- Updated selectors to relevant;
- Removed "merchantMetrics" and "reviewsLink" keys from the output object (this info is not represented on the page);
- Updated SDK to 1.2.0.

2021-05-26 01:42 UTC, pocesar commented on src/main.js
>              return page.goto(request.url, {
`gotoFunction` is now `preNavigationHooks`. it should be 

```js
preNavigationHooks: [async ({}, gotoOptions) => { 
  gotoOptions.waitUntil = 'load';
  gotoOptions.timeout = 18000;
}]
```

2021-05-26 01:43 UTC, pocesar commented on src/main.js
> +                waitUntil: 'domcontentloaded',
`'domcontentloaded'` or `'load'`?

2021-05-26 01:43 UTC, pocesar commented on src/main.js
> +                headless: true,
`headless` or `useChrome`?

2021-05-26 01:44 UTC, pocesar reviewed
package-lock.json can be deleted (and .gitignored)
`productDetails` seems to be always `null`, not sure if it's a problem with the selector or it's like the 'merchantMetrics' issue (non-existent anymore) 
update the Dockerfile to use the latest chrome images `apify/actor-node-puppeteer-chrome`

overall, the resulting dataset looks good

2021-05-26 08:40 UTC, OlehVeselov92 commented
Made changes. Sorry for silly mistakes in crawler options) 
About  "productDetails":
It was originally null in the actor. 

In description on the page there is no full item description. Only first two sentences or so, and three dots.
Maybe that's why somebody decided to make it null.
Anyway, first two sentences is better then null) So i added it to the output.

2021-05-26 16:24 UTC, pocesar commented on .gitignore
> -apify_storage
this file needs to stay 😄 
and add `package-lock.json` here

2021-05-26 16:28 UTC, pocesar requested changes
looks great now, just bring back `.gitignore` with the extra line 👍🏻

2021-05-27 15:02 UTC, pocesar approved these changes
🚀

2021-05-27 15:02 UTC, merged